name: "Test"
on:
  workflow_dispatch:  # Allow manual triggering of workflow
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'packages/**.nix'
      - 'nixosConfigurations/**'
      - '.github/workflows/**'
  push:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'packages/**.nix'
      - 'nixosConfigurations/**'
      - '.github/workflows/**'

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
    - run: echo "The following changes do not evaluate as proper nix expressions - https://nix.dev/manual/nix/2.17/command-ref/new-cli/nix3-flake-check"
    
  ilia:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'packages/ilia.nix') || contains(github.event.files.added, 'packages/ilia.nix') || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#ilia

  rofication:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'packages/rofication.nix') || contains(github.event.files.added, 'packages/rofication.nix') || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#rofication

  regolith-powerd-inputd-displayd:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'packages/regolith-powerd.nix') || 
             contains(github.event.files.modified, 'packages/regolith-inputd.nix') || 
             contains(github.event.files.modified, 'packages/regolith-displayd.nix') || 
             contains(github.event.files.modified, 'packages/libtrawldb.nix') || 
             contains(github.event.files.added, 'packages/regolith-powerd.nix') || 
             contains(github.event.files.added, 'packages/regolith-inputd.nix') || 
             contains(github.event.files.added, 'packages/regolith-displayd.nix') || 
             contains(github.event.files.added, 'packages/libtrawldb.nix') || 
             github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#regolith-powerd
    - run: nix build .#regolith-inputd
    - run: nix build .#regolith-displayd
    - run: nix build .#libtrawldb

  sway-regolith:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'packages/sway-regolith.nix') || contains(github.event.files.added, 'packages/sway-regolith.nix') || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#sway-regolith

  trawl:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'packages/trawl.nix') || contains(github.event.files.added, 'packages/trawl.nix') || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#trawl

  xrescat:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'packages/xrescat.nix') || contains(github.event.files.added, 'packages/xrescat.nix') || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#xrescat

  fhs:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'packages/fhs.nix') || contains(github.event.files.added, 'packages/fhs.nix') || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#fhs

  virtual-machine:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'nixosConfigurations/vm') || contains(github.event.files.added, 'nixosConfigurations/vm') || github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.vm.config.system.build.vm
    
  regolith-session:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'packages/regolith-session.nix') || 
             contains(github.event.files.modified, 'packages/regolith-session-wayland.nix') || 
             contains(github.event.files.modified, 'packages/regolith-session-x11.nix') || 
             contains(github.event.files.added, 'packages/regolith-session.nix') || 
             contains(github.event.files.added, 'packages/regolith-session-wayland.nix') || 
             contains(github.event.files.added, 'packages/regolith-session-x11.nix') || 
             github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#regolith-session
    - run: nix build .#regolith-session-wayland
    - run: nix build .#regolith-session-x11
    
  status-bar:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'packages/i3-swap-focus.nix') || 
             contains(github.event.files.modified, 'packages/i3status-rs.nix') || 
             contains(github.event.files.modified, 'packages/i3xrocks.nix') || 
             contains(github.event.files.added, 'packages/i3-swap-focus.nix') || 
             contains(github.event.files.added, 'packages/i3status-rs.nix') || 
             contains(github.event.files.added, 'packages/i3xrocks.nix') || 
             github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#i3-swap-focus
    - run: nix build .#i3status-rs
    - run: nix build .#i3xrocks

  regolith-config-styles-essentials:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.files.modified, 'packages/regolith-wm-config.nix') || 
             contains(github.event.files.modified, 'packages/regolith-xresources.nix') || 
             contains(github.event.files.modified, 'packages/regolith-ftue.nix') || 
             contains(github.event.files.modified, 'packages/remontoire.nix') || 
             contains(github.event.files.modified, 'packages/regolith-styles.nix') || 
             contains(github.event.files.modified, 'packages/regolith-look-default.nix') || 
             contains(github.event.files.modified, 'packages/regolith-look-extra.nix') || 
             contains(github.event.files.added, 'packages/regolith-wm-config.nix') || 
             contains(github.event.files.added, 'packages/regolith-xresources.nix') || 
             contains(github.event.files.added, 'packages/regolith-ftue.nix') || 
             contains(github.event.files.added, 'packages/remontoire.nix') || 
             contains(github.event.files.added, 'packages/regolith-styles.nix') || 
             contains(github.event.files.added, 'packages/regolith-look-default.nix') || 
             contains(github.event.files.added, 'packages/regolith-look-extra.nix') || 
             github.event_name == 'workflow_dispatch' }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: sandptel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#regolith-wm-config
    - run: nix build .#regolith-xresources
    - run: nix build .#regolith-ftue
    - run: nix build .#remontoire
    - run: nix build .#regolith-styles
    - run: nix build .#regolith-look-default
    - run: nix build .#regolith-look-extra
